const CartActionTypes = {
	REMOVE_ONE_CART_ITEM: "REMOVE_ONE_CART_ITEM",
	REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
	ADD_ITEM: "ADD_ITEM",
	TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN"
};

export default CartActionTypes;
